Bugfix: Create RELEASE_DIR with create_release.py and remove volume mount for release directory (#10)
This commit fixes a permission error during the release artefact creation stage of
the Qualcomm CI build. In our latest build this is what we saw:
PermissionError: [Errno 13] Permission denied: '/home/dev/Qualcomm/release/imdt_qcs8550_sbc_prebuilt_release_v1.2.0'

This issue happens because we mount a non-existent directory into
the container as a volume. This issue is fixed by simply removing
the volume mount and letting create_release.py create the release
directory.