Bugfix: fix unset variable error on new development state file creation (#12)
This commit resolves a `project: unbound variable` error in the event that a
state file for the triggering manifest repository has not been
previously created, causing development build attempts to fail when
polling for changes. When the error happens this is the log you get:

No previous state file found for imdt-qcom-manifest-dev. Assuming first build. Continuing build process...
./scripts/poll-development-repo.sh: line 110: project: unbound variable
Error: Process completed with exit code 1.

Previously, upon execution of poll-development-repos.sh, $project
was only defined on the condition that a state file existed under the
corresponding triggering repository name in the following code:

    if [ -f "$state_file" ]; then
        #first line: PROJECT | DATE | RESULT
        IFS='|' read -r project last_date last_result < "$state_file"
        last_date=$(xargs <<< "$last_date")
        last_result=$(xargs <<< "$last_result")

Usage of this variable is redundant, and has thus been changed to the
non-conditional, identical in purpose `$project_name` to ensure
successful execution on initial runs.